### PR TITLE
Update popup text on maps on user/admin dashboard, landing page

### PR DESCRIPTION
**Pull request by misaugstad**
- On the choropleths, the 100% complete neighborhoods' text have been modified to allow users to audit those neighborhoods even though they are complete
- On the user dashboard, the map popup text now matches that of the choropleths

Related to issues #622 and #464

### CODE REVIEW

**Comment by misaugstad** [comment]
@manaswis this should be good to go finally

**Comment by manaswis** [comment]
Looks like @adash12 added logging for the clicks as well in this PR. @misaugstad Could you update the PR description to reflect the same? I am assuming you tested those changes in the PR he submitted, so I am testing them again.

Based on testing this PR: when I click a neighborhood in the user dashboard, I get the following error:

image

**Comment by manaswis** [comment]
@misaugstad Also, you haven't made any changes to the admin dashboard pop-ups, correct? The title suggests otherwise.

**Comment by misaugstad** [comment]
>you haven't made any changes to the admin dashboard pop-ups, correct? The title suggests otherwise.

The following has been done:
>On the choropleths, the 100% complete neighborhoods' text have been modified to allow users to audit those neighborhoods even though they are complete

This includes the choropleth on the admin dashboard. The title is accurate :)

>Based on testing this PR: when I click a neighborhood in the user dashboard, I get the following error:

Fixed!

**Comment by manaswis** [comment]
Okay. The user dashboard works. 

Re: admin dashboard. I got confused between the map from the "Map" tab and the map from the "Analytics" tab.  The choropleth in the analytics tab has the changes.

**Pull request merged**
