### PR TITLE
2212 Rename User-facing Instances of "Occlusion" terminology

### LINKED ISSUE #2212: Rename "Occlusion" to "Can't see the sidewalk" in labeling guide
The word occlusion is just what we use on the back end and in papers when we can describe what we mean by it. Anything user facing should use the phrase "Can't see the sidewalk".

### PR DESCRIPTION
**Pull request by jacknussbaum**
Resolves #2212 

Renames all user-facing instances of the term "Occlusion" to "Can't See the Sidewalk" within the Labeling guide. 

Before:

After:

##### Things to check before submitting the PR 
- [X] If there is a visual design component, I've posted before/after screenshots on the relevant issue thread and have been given a thumbs up on my design.
- [X] I've made sure my code and comments follow the [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide).
- [X] I've tested on multiple browsers.
- [X] I've tested as an Anonymous user, Registered user, and as a Turker.
- [X] I've verified that this PR is set to merge into the develop branch.
- [X] I've written a descriptive PR title.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Hi @jacknussbaum,

Is this your first PR? If so, congrats. Woohoo!!

This looks largely good to me; however, a few things:
- First, best to embed images into your PR or Issues that we can see without clicking. You should use the markdown `alt text` format. I changed this for you above.
- Second, there are lots of files in this PR that need to be removed, including:
  - All the *ivy2 stuff
  - docker-compose.yml
  - The file called simply 'f'

**Comment by jacknussbaum** [comment]
It is my first PR! Thank you!

Thanks for changing the images.

I reverted the two commits that included unnecessary files and will re-commit them!

**Comment by jacknussbaum** [comment]
This PR can be deleted.

**Comment by misaugstad** [comment]
closing in favor of #2301

**Pull request closed without merging**
