### PR TITLE
1530 Validation interface zoom level bug fix

### LINKED ISSUE #1530: How can I tell what zoom level I'm at in validation interface?
How can I tell what zoom level I'm at in validation interface? There doesn't seem to be any way I can tell other than playing with the zoom in and out controls.

### PR DESCRIPTION
**Pull request by htadeusiak**
Fixes #1530 

Originally, the zoom level buttons would enable/disable when ZoomControl was created/called. However, as Jon discovered, this did not work with each new validation screen.

I've updated ZoomControl and validation to check if the buttons need to be enabled/disabled whenever a user starts a validation mission and after every label validation. This should address the bug Jon pointed out.

After:
test2

### CODE REVIEW

**Comment by misaugstad** [comment]
@htadeusiak I still seem to be having zoom button problems on this branch. I seem to have the ability to zoom correctly, but the buttons don't seem to be grayed out correctly all the time.

**Comment by htadeusiak** [comment]
@misaugstad 
Could you screen shot an example? I'm having a bit of trouble finding this other bug.

**Comment by htadeusiak** [comment]
I just edited the code a little, maybe it fixed the bug you we're seeing.

**Comment by misaugstad** [comment]
Oops, the issue was that I was using the branch `1530-validation-interface-zoom-level-ui-update` instead of `1530-validation-interface-zoom-level-ui-update-bug` -- too similarly named :sweat_smile:

**Comment by htadeusiak** [comment]
Yup, sorry my bad. I won't do that in the future.

**Pull request merged**
