### PR TITLE
Fixed navbar styling changes

### LINKED ISSUE #816: Menu tab in navbar is unusable on smaller windowed screens
The navbar automatically hides the "retake tutorial" "faq" and "sign in" buttons into a collapsible pane called "menu" when the browser window is below a certain width. Unfortunately, it is near impossible to navigate menu; the options jump to the left side of the screen, appear in a very short scrollable dropdown, and have a transparent background until hovered:

image

This is also the case on the live site:
image

Since our users may use these smaller resolutions, we should probably either disable the "menu" dropdown and leave the navbar links in place on smaller res screens, or fix the positioning of the items in this dropdown.

### LINKED ISSUE #908: See Results in NavBar Doesn't Highlight on Mouse Over
Start Mapping has mouseover highlighting:

image

The See Results button does not (but should):
image

### LINKED ISSUE #918: Need to Support Right-Clicking to Open In New Tab on Navbar
image

### PR DESCRIPTION
**Pull request by sbower213**
Resolves #816 
Resolves #908
Resolves #918

The See Results button now changes color on hover and the menu is not condensed into a dropdown on thinner screens.

Since my pull request #829 had some old code in it, it was easier to make a new PR with the desired changes than to go and edit out the code that was out of date. This PR should be the one that is merged into master.

### CODE REVIEW

**Comment by manaswis** [comment]
Hmm, I just tested this. The new changes automatically positions the buttons. However, I think more updates are needed before it can be merged.

Left: w/ New changes  -----------------------------------------    Right: Old 

image

Will have to push this post-CHI.

**Comment by manaswis** [comment]
@johannkm Could you work on this closing this issue? The fix is there but it doesn't look great visually. See the screenshots above. Also, there are some conflicts now with latest changes that are made.

**Comment by manaswis** [comment]
@johannkm I tested this PR. The hover color seems to be gone now (#908) for both Start Mapping and See Results.

**Comment by johannkm** [comment]
Huh, guess I didn't notice that I broke it when I made the changes for smaller screens. Pushed a fix.

screen shot 2017-10-02 at 11 20 19 pm

**Comment by sarahsmo** [comment]
@johannkm I noticed that your navbar fixes were pushed to develop so I pulled the changes and tested what they look like. I notice that for small screens the menu drop down is still pretty funky. Is this something that you plan to change? If not I might want to work on it because it directly effects my mobile development for the site. 

image

**Comment by johannkm** [comment]
@sarahsmo that's definitely not the behavior I intended. This is the behavior I see on develop:
screen shot 2017-10-19 at 2 48 25 pm

**Comment by sarahsmo** [comment]
@johannkm yeah sorry about that! that was my fault, i tested it right before manaswi merged and closed the PR. It looks great now!

**Pull request merged**
