### PR TITLE
1318 update webpage email

### LINKED ISSUE #1318: Please change listed email to sidewalk@cs.uw.edu
Please change the correspondence email to sidewalk@cs.uw.edu on our webpage (all externally facing parts of site).

I just subscribed all of you.

### PR DESCRIPTION
**Pull request by tadg99**
Resolves #1318 

Changes the email address on the webpage from sidewalk@umiacs.umd.edu to sidewalk@cs.uw.edu

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Woohoo. First PR! Given that we had to change four files here, I wonder if it makes sense to put this email address into a variable that pages then just use. 

I’m guessing this will be a fast code review for either Aileen or Mikey.

**Comment by misaugstad** [comment]
@tadg99 could you actually redo this quick where you branch off of the develop branch to begin with instead of the master branch?

**Comment by misaugstad** [comment]
@tadg99 feel free to just make a new branch and new PR to start from scratch

**Comment by misaugstad** [comment]
Closing b/c a new PR was opened for this (PR #1333 )

**Pull request closed without merging**
