### PR TITLE
Jump fix

### PR DESCRIPTION
**Pull request by kotarohara**

### CODE REVIEW

**Comment by manaswis** [comment]
I tested it out. The jumps worked perfectly and I am able to finish the neighborhood. Although, there were a few issues:

Issue 1: After the old mission is complete, here are the series of screenshots:

mission_complete

The newly assigned neighborhood is Mount Pleasant. Missed taking the screenshot. After I click OK to the mission text, the following screen is shown.
jumped to deanwood
**This is a bug.** This bug occurs even between two missions (old and new) in the same neighborhood.

Then the new mission is started in the assigned neighborhood.
new_mission

Issue 2: Jumping actually increases the mission progress significantly. 

The first option increases the mission progress gradually (~1%) and sometimes reduces too.
[https://youtu.be/60rdcNztxGc?t=7s](https://youtu.be/60rdcNztxGc?t=7s)

The second option increases the mission progress significantly! It becomes 18% to 49 % to 100%.
See video (starts at 36s): 
[https://youtu.be/60rdcNztxGc?t=36s](https://youtu.be/60rdcNztxGc?t=36s)

**Comment by jonfroehlich** [comment]
**Issue 1**
Unfortunately, your description was not entirely clear to me. I see two potential problems:

- When you start a new neighborhood, it looks like the stats are not cleared (e.g., you put a red rectangle around 6.2 miles and 48 labels but these should both be zero)
- You get a jump message to 'Deanwood' even though you are in Mt Pleasant.

**Issue 2**
1. When choosing the first option, I agree that the progress bar probably should not increase. What's likely happening is that the current location that you are standing when you click jump to another area, is being marked as audited. Thus, you are slowly, one GSV location at a time, auditing that neighborhood

2. For the second option, I don't think this is a bug. As soon as you say 'I cannot go in the direction that you want me to walk," we have to mark that segment as unauditable/unwalkable, so your mission progress jumps as a result (I'm not sure if @kotarohara does this by subtracting out the unauditable areas or by simply giving you credit for walking what you cannot walk). A related question is: @kotarohara, when a user marks a segment as unauditable/unwalkable, do we store that in the database so that we can differentiate it on analysis?

**Comment by manaswis** [comment]
Re: Issue 1

> Are there things that I missed here? Again, you did not explicitly spell out the problems so we are only left to infer proper behavior. You say "This is a bug" but not what the bug is

> You get a jump message to 'Deanwood' even though you are in Mt Pleasant.

Yes, I just read the description. I missed adding it explicitly (was too sleepy when writing this :)). Sorry about that. I have updated my description comment.

> When you start a new neighborhood, it looks like the stats are not cleared (e.g., you put a red rectangle around 6.2 miles and 48 labels but these should both be zero)

I missed this bug when I posted this. Yes, these should have been zero.

Re: Issue 2

> When choosing the first option, I agree that the progress bar probably should not increase. What's likely happening is that the current location that you are standing in when you click jump to another area, is being marked as audited. Thus, you are slowly, one GSV location at a time, auditing that neighborhood

Also, the first option shouldn't decrease the progress either. There were two instances in the video when that happened: at [7s](https://youtu.be/60rdcNztxGc?t=7s) and [37s](https://youtu.be/60rdcNztxGc?t=37s)

**Comment by jonfroehlich** [comment]
@manaswis, did you test this to your satisfaction?

@kotarohara, did you fix the new Issues that @manaswis identified?

**Comment by kotarohara** [comment]
No, they are not fixed and there should be open issues.

**Pull request merged**
