### PR TITLE
#2697 Add Validation Info to Gallery Cards

### LINKED ISSUE #2697: Adding in validation info into Sidewalk Gallery cards
Given our experience with some data messiness in Chicago (struggling labelers), I think it would be helpful to add crowdsourced judgement info to Sidewalk Gallery (and perhaps other validation interfaces as well)

image

Would be nice to sort or filter by this info as well. See: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2358

Made the mock in pptx (as usual) here:
[LabelCorrectnessMockForSidewalkGallery.pptx](https://github.com/ProjectSidewalk/SidewalkWebpage/files/7390931/LabelCorrectnessMockForSidewalkGallery.pptx)

### PR DESCRIPTION
**Pull request by zoekaputa**
Resolves #2697

Adds validation information to the Gallery Page in each card and in modals, using a thumbs up and a thumbs down image along with a count for each, indicating the agree count and the disagree count of each attribute. 
- Oh hover of either the thumbs up or thumbs down image, a tooltip appears with the label "Agree" or "Disagree,"  respectively. These labels change based on the language the page is being displayed in.
- The original design showed "Agree" and "Disagree" above each image, rather than in a tooltip. However, because the Spanish translations are so long, Mikey and I decided it would be better to display these labels in tooltips. Some other options we could explore include finding shorter translations for the terms "Agree" and "Disagree."
- The thumbs up and a thumbs down images are stored as PNGs.

##### Before:
Cards:
Screen Shot 2023-02-10 at 11 17 58 AM

Modal:
Screen Shot 2023-02-10 at 11 18 09 AM

##### After:
Cards:
Screen Shot 2023-02-10 at 10 55 02 AM   Screen Shot 2023-02-10 at 10 55 11 AM
Screen Shot 2023-02-10 at 10 59 37 AM   Screen Shot 2023-02-10 at 11 01 06 AM
Screen Shot 2023-02-10 at 11 01 22 AM

Modal:
Screen Shot 2023-02-10 at 10 55 25 AM

#### Testing instructions
1. Run the branch locally
2. Navigate to the Gallery page
3. The validation info should be visible on each card
4. Hover over the agree and disagree displays to view the Agree/Disagree tooltip label of each
5. Click on a card to open a modal. Here, you should also be able to see the validation info. Again, hover over the agree and disagree displays to view the tooltip label of each

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Great work as usual @zoekaputa. If we agree/disagree on the current card, do the counts next to the thumbs update appropriately?

**Comment by zoekaputa** [comment]
@jonfroehlich As of now no, is that something I should look into implementing?

**Comment by misaugstad** [comment]
Agreeing with @jonfroehlich! Any time we validate, it should update both the thumbs up/down icons and the color of the card (like it already does)

**Comment by misaugstad** [comment]
Okay I have no idea how this happened. Somehow the PR was set to merge develop into the 2697 branch instead of the other way around; I don't know if it was like this from the start. When I manually merged develop into the branch, Github decided that it meant that the PR was merged... So I guess I'm going to make a copy of the PR that points in the correct direction once it's ready!

**Pull request merged**
