### PR TITLE
Resolves #453 - Onboarding - All yellow arrows can now flash

### LINKED ISSUE #453: Tutorial: Arrows Should Flash to Draw Attention and Be Consistent
These arrows should flash to draw more attention to them and be consistent with the rest of the tutorial interface when things are highlighted in yellow.

image

### PR DESCRIPTION
**Pull request by maddalihanumateja**
Resolves #453. drawBlinkingArrow() uses javascript's requestAnimationFrame function to update the arrow color. The blink_function_identifier variable maintains a reference to any such function calls so that we can clear the flashing arrows during state change and POV change. The arrows flash with a period of 0.5s.

### CODE REVIEW

**Comment by manaswis** [comment]
@maddalihanumateja I think you misunderstood the issue. Only the yellow arrows need to be flashing. You currently have all arrows as flashing, which makes multiple elements on the interface flash at the same time. Flashing is for drawing attention to one element.

**Comment by maddalihanumateja** [comment]
I actually changed it at the last moment. Making all arrows flash seemed to make more sense.

**Comment by manaswis** [comment]
Also, when making these changes, merge the new changes from develop into your branch.

**Comment by manaswis** [comment]
> I actually changed it at the last moment. Making all arrows flash seemed to make more sense.

How so? Where do you focus when two things are flashing at the same time? Its also visually disorienting when multiple things are flashing; you don't know where to look.

**Comment by maddalihanumateja** [comment]
In some states you need to click on the flashing label buttons while reading the related instruction. That is why I thought that Jon actually meant for the arrows to be flashing when the instruction was presented. But now I see why say that might be an issue. Both the label button and arrows are flashing at the same time. I'll change that

**Comment by maddalihanumateja** [comment]
I've made the change. Only yellow arrows will flash now.

**Pull request merged**
