### PR TITLE
Addresses Issue #890 - Update About Page Personnel

### LINKED ISSUE #890: Update About Page Personnel
It's outdated.

http://sidewalk.umiacs.umd.edu/about

Need to add:
- Ryan Holland @r-holland 
- Chirag @chishankar 
- Aditya @adash12 
- Steven @sbower213 
- Sage Chen @sagec108 (as alumni)

image

### PR DESCRIPTION
**Pull request by jonfroehlich**
Resolves #890. Added new summer 2017 Project Sidewalk members. Moved old members to
alumni. Updated our mission text.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
I couldn't really see what my modifications look like because I don't have PS running locally on my machine and I just used notepad++ to edit. :)

**Comment by manaswis** [comment]
You need to change the base to develop. You could do that using the PR's edit

image

**Comment by manaswis** [comment]
> I couldn't really see what my modifications look like because I don't have PS running locally on my machine and I just used notepad++ to edit. :)

You can see the changes you made here: https://github.com/ProjectSidewalk/SidewalkWebpage/pull/957/files

Its the "Files Changed" above - 
image

**Comment by jonfroehlich** [comment]
Oops. Switched base to develop. I was specifically stating that I could not see what my modifications look like visually because I am not running PS server locally on my machine. I can, of course, see changes using git's tools.

**Comment by misaugstad** [comment]
@jonfroehlich there were some issues with the formatting of the html, but seeing as you aren't running the code locally, I fixed it for you :stuck_out_tongue:

**Pull request merged**
