### PR TITLE
#2752 add amsterdam logos

### LINKED ISSUE #2752: Add logos for Amsterdam
##### Brief description of problem/feature
I think we'll want to add logos for the City of Amsterdam, Amsterdam Intelligence, and World Enabled to our site. Not sure if these are all going in the Collaborators section or if we are finding a new solution given the number of logos we are starting to rack up ;)

Here are the City of Amsterdam and Amsterdam Intelligence logos. We're just waiting on the World Enabled one.

City of Amsterdam
GASD_E_sponsor_pms

Amsterdam Intelligence
ai logo_white

### PR DESCRIPTION
**Pull request by zoekaputa**
Resolves #2752 

Adds logos for City of Amsterdam, Amsterdam Intelligence, and World Enabled to the Collaborators section of the home page for Amsterdam only. Note I changed the heights of the City of Amsterdam and Amsterdam Intelligence logos using CSS as they were very large otherwise.

##### Before/After screenshots (if applicable)
Before:
Screen Shot 2022-01-04 at 1 19 21 PM

After (on Amsterdam site):
Screen Shot 2022-01-05 at 2 09 26 PM

After (on Columbus site):
Screen Shot 2022-01-05 at 2 12 05 PM

##### Testing instructions
1. Modify the `SIDEWALK_CITY_ID` line in the `docker-compose.yml` to be `amsterdam`.
2. Run locally and navigate to the Collaborators section of the home page to see the added logos.
3. Modify the `SIDEWALK_CITY_ID` line in the `docker-compose.yml` to be an other city ID.
4. Run locally and navigate to the Collaborators section of the home page to see no added logos.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Woohoo! Your first PR!

Some quick feedback:
- Can you make the two Amsterdam logos continuguous (i.e., next to each other). I would put World Enabled first, then City of Amst, then amsterdam intelligence
- Can you use a [CSS grid](https://css-tricks.com/snippets/css/complete-guide-grid/) to make a 2x3 grid (2 rows, 3 cols) so that the logos are better aligned
- Finally, can you make sure to use lossless compression (PNG) and resave the logos to approximately the size we need for the website we don't waste user bandwidth?

**Comment by zoekaputa** [comment]
> Woohoo! Your first PR!
> 
> Some quick feedback:
> 
> * Can you make the two Amsterdam logos continuguous (i.e., next to each other). I would put World Enabled first, then City of Amst, then amsterdam intelligence
> * Can you use a [CSS grid](https://css-tricks.com/snippets/css/complete-guide-grid/) to make a 2x3 grid (2 rows, 3 cols) so that the logos are better aligned
> * Finally, can you make sure to use lossless compression (PNG) and resave the logos to approximately the size we need for the website we don't waste user bandwidth?

I made these updates! Using grids made the logos significantly smaller because of the container width, even more so on the Columbus page. Let me know if you would prefer me change the grid layout in any way.

**Comment by jonfroehlich** [comment]
Great. Thanks @zoekaputa. I think this looks great.

(As a process suggestion, I think generally it would be best to *not* have edited the first textbox and, instead, added in the new screenshots, etc. in the "I made these updates!" comment box. That way, we could compare to your initial PR screenshots and also have the context for our discussions)

**Comment by misaugstad** [comment]
@jonfroehlich my main concern is how small the UIC logo looks compared to the others after this change...

Before
Screenshot from 2022-01-06 10-56-56
After
Screenshot from 2022-01-06 10-57-00

Do you think that that looks bad enough that we want to try something else?

**Comment by jonfroehlich** [comment]
This is simply because of the different logo ratios, which we either fix in the raw files (the .pngs) so that everything has relatively equal widths/heights or we use something like a max-height css command.

Honestly, for now, I say we push this. Once it's on -test, it's easy enough for me to play around with it and polish, as necessary.

**Comment by zoekaputa** [comment]
Thank you for the advice @jonfroehlich. Would you like me to address the address the size difference of the UIC logo? If not, I'm unable to merge this branch myself because I'm not an authorized user.

**Comment by jonfroehlich** [comment]
Generally, @misaugstad is the one to approve and merge. Typically, the author of the PR does not merge themselves...

I'd encourage you to move on to another one of your assigned Issues in the mean time. 

Nice work @zoekaputa!

**Review by misaugstad — COMMENTED** [review]
Hi @zoekaputa sorry I had prepared this PR review but it looks like I forgot to hit 'Submit review' last week :sob: I just had a couple small style things I'd like to see fixed up before merging! :) Otherwise it looks good!

**Review by misaugstad — APPROVED** [review]
Looks good, thanks @zoekaputa !!

**Pull request merged**
