### PR TITLE
769 clear tutorial labels

### LINKED ISSUE #769: Labels from tutorial can be retrieved by using undo and redo buttons repeatedly
After completing the tutorial, I can retrieve labels placed in the tutorial by using undo and redo buttons in the mission. In the picture below, I had not placed any labels beside those in the tutorial.

image

### PR DESCRIPTION
**Pull request by sagec108**
Resolves #769. 

Action stack is cleared after onboarding. Users are no longer able to retrieve tutorial labels or previous missions labels while in a different mission using the undo & redo buttons.

### CODE REVIEW

**Comment by maddalihanumateja** [comment]
The action stack is only cleared for the first mission after onboarding. Good job Sage but this needs to be done at the end of every mission. The problem actually persists for other missions. I can still use undo to get back the labels of, for example, the first mission when starting the second mission,.

**Comment by sagec108** [comment]
I was specifically solving tutorial labels being retrievable. We did not explicitly agree on resetting the action stack after each mission. If this is the behavior we want, I can easily implement it.

**Comment by maddalihanumateja** [comment]
Thanks. If its an easy fix go ahead and implement it. I was verifying this based on your pull request comment "no longer able to retrieve tutorial labels **or previous missions labels while in a different mission**"

**Comment by sagec108** [comment]
I did it for after the tutorial (once you do a tutorial you can't retrieve previous mission labels). I did not modify regular missions, which I will do later.

**Comment by maddalihanumateja** [comment]
1. The numOnboardingLabels in Onboarding.js is initialized but never used. Is there a reason it should exist? 
2. Please leave a small comment explaining what the reset () function does in ActionStack.js
3. There seem to be some conflicts. Did you merge changes from develop into your branch?

**Comment by sagec108** [comment]
@maddalihanumateja Everything you asked for should now be resolved!

**Pull request merged**
