### PR TITLE
Resolves 1664: modified dockerfile and updated base image to handle the deprecated java 8 package

### LINKED ISSUE #1664: oracle-java8-installer has no installation candidate
When running `make dev` "for the first time" and building the container, it exits and reports that `Package 'oracle-java8-installer' has no installation candidate`. Is this something you might be able to help us with @athersharif? Here is the full log:

```andrew@andrew:~/IdeaProjects/Sidewalk (develop)$ make dev
projectsidewalk-db is up-to-date
Starting projectsidewalk-db ... done
Building web
Step 1/10 : FROM node:10.10.0
 ---> d0d12094f6ab
Step 2/10 : RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
 ---> Using cache
 ---> a764cb3cc428
Step 3/10 : RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
 ---> Using cache
 ---> eb74636cde2e
Step 4/10 : RUN apt-get -o Acquire::Check-Valid-Until=false update && apt-get -o Acquire::Check-Valid-Until=false upgrade -y
 ---> Using cache
 ---> 7d937fa480d7
Step 5/10 : RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list &&   echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list &&   apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 &&   echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list &&   apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 &&   apt-get install -y apt-transport-https
 ---> Using cache
 ---> 3b7110203a83
Step 6/10 : RUN apt-get -o Acquire::Check-Valid-Until=false update &&   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections &&   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections &&   apt-get install -y     oracle-java8-installer     unzip     python-dev     python-pip     libblas-dev     liblapack-dev     gfortran     python-numpy     python-pandas     sbt &&   apt-get autoremove &&   apt-get clean
 ---> Running in 1987ede70143
Hit http://archive.debian.org jessie-backports InRelease
Get:1 https://dl.bintray.com  InRelease
Ign https://dl.bintray.com  InRelease
Get:2 http://ppa.launchpad.net xenial InRelease [17.6 kB]
Get:3 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:4 https://dl.bintray.com  Release.gpg [821 B]
Ign http://deb.debian.org jessie InRelease
Get:5 https://dl.bintray.com  Release [815 B]
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:6 http://archive.debian.org jessie-backports/main amd64 Packages [1171 kB]
Get:7 http://ppa.launchpad.net xenial/main Sources [20 B]
Get:8 http://ppa.launchpad.net xenial/main amd64 Packages [20 B]
Get:9 https://dl.bintray.com  Packages [3424 B]
Get:10 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Get:11 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]
Fetched 11.2 MB in 26s (419 kB/s)
Reading package lists...
W: Size of file /var/lib/apt/lists/security.debian.org_debian-security_dists_jessie_updates_main_binary-amd64_Packages.gz is not what the server reported 824457 824527
Reading package lists...
Building dependency tree...
Reading state information...
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get -o Acquire::Check-Valid-Until=false update &&   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections &&   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections &&   apt-get install -y     oracle-java8-installer     unzip     python-dev     python-pip     libblas-dev     liblapack-dev     gfortran     python-numpy     python-pandas     sbt &&   apt-get autoremove &&   apt-get clean' returned a non-zero code: 100
Makefile:18: recipe for target 'docker-run' failed
make: *** [docker-run] Error 1
```

### PR DESCRIPTION
**Pull request by athersharif**
fixes #1664

### CODE REVIEW

**Comment by misaugstad** [comment]
@athersharif thanks for this! Going to try to test today.

Could you give a bit more info on the changes you are making? What is the old image (OS versions, etc) and what is the new image? Do you expect this new image to be supported longer? Or are you picking one that is as close as possible to the old one but not EOL'd so that we have to change as little as possible?

**Comment by athersharif** [comment]
the old image was node's official image, which uses `jessie`, and then trying to install java8. in this change, we're switching to java's official image, which is based on the `stretch` distribution. we should definitely update to a higher version of java in the future though but because this image is officially supported by java, i'm hoping we'll have a much more reliable support for java8 and won't have to rely on various PPAs.

**Comment by misaugstad** [comment]
Thanks @athersharif! And this seems to fix the issue and the website seems to be working as normal with the new image! I'm just going to get in touch with @mechanicjay to see if he can foresee any issues with updating the production Dockerfiles accordingly along with when he would be able to make that update. We want to keep the dev environment and prod environment as similar as possible :)

**Comment by misaugstad** [comment]
@annieyx you definitely were not supposed to do that :sweat_smile: I can deal with fixing it, but make sure not to merge any PRs in the future, I should be the only one merging the PRs because merging them triggers the test servers to redeploy :grin:

**Pull request merged**
