### PR TITLE
Resolves #1134: Add requirements.txt and autoinstaller for project's python scripts

### LINKED ISSUE #1134: Add python library install commands to build files
We have a few Python scripts that are used, at least in the mturk branch, and they require installation of a few external libraries. When building the project, we should be automatically checking that those libraries are installed, and installing them if not.

Side note: all the Python scripts have been put in the root directory... We have enough where it would make sense to put them in a python sub directory or something.

### PR DESCRIPTION
**Pull request by tongning**
Resolves #1134 

This PR adds a requirements.txt file for the Python packages needed by the scripts in the root directory of the project:

* anonymize.py
* connect.py
* deploy.py
* fetch_sql_dump.py
* hit_approve_assignment.py
* hit_approve_bonus.py
* test_deploy.py

It also adds a section in build.sbt so that the `pip install` command can be invoked from sbt using `sbt compile`. This process assumes that `pip` is already installed on the system. Tested on a fresh Ubuntu 16.04 VM.

### CODE REVIEW

**Comment by tongning** [comment]
Also, during the meeting we brought up the question of whether we should assume pip is installed or whether we should attempt to detect pip before proceeding. For now, the auto-install is only invoked on `sbt compile` and not `sbt run` (at least in my testing), so I don't think the lack of pip would prevent the app from launching.

**Comment by misaugstad** [comment]
@manaswis I don't believe pip is installed on the server. How have you been installing Python libraries on the server in the past? Does it require emailing UMIACS and asking them to do it?

**Comment by misaugstad** [comment]
Waiting on this one to see how installing packages and such works once we dockerize Project Sidewalk (#593).

**Comment by misaugstad** [comment]
This PR has been replaced by #1475

**Pull request closed without merging**
