### PR TITLE
Fix #269: "Intersection done dialog pops up before it is completed"

### LINKED ISSUE #269: Intersection done dialog pops up before it is completed
Lee: In the first real mission I did (River Terrace, D.C.), a message popped up telling me that I was done and should move on, but I had only actually finished 3/4 corners.

### PR DESCRIPTION
**Pull request by Soben713**
Fixes #269.

Calculating the portion of the panorama scene that the user has viewed was more complicated than I expected. Although I tried to use the simplest possible algorithm, but it is still quite complicated. I can explain it to whoever that tries to review this PR.

### CODE REVIEW

**Comment by Soben713** [comment]
Calculating the portion of the panorama scene that the user has viewed was more complicated than I expected. Although I tried to use the simplest possible algorithm, but it is still quite complicated. I can explain it to whoever that tries to review this PR.

**Comment by jonfroehlich** [comment]
Can you just summarize what you did below?

**Comment by Soben713** [comment]
@jonfroehlich Sure.

The heading of the panorama indicates the angle in which the user is looking at and could be any number between 0 and 360. We constantly track the heading to detect when the whole scene has been viewed. The problem is that the user might alter between moving clockwise and counter-clockwise (this is what was not considered in the original code and caused [this](https://www.youtube.com/watch?v=pOHmRuIicMk&feature=youtu.be) problem to happen).

To detect this, I store and constantly update two variables: `viewedCWTransformed` and `viewedCCWTransformed`. The first one stores the size of the largest arc from the initial heading that the user has seen while moving clockwise. Similarly, the second variable stores the same thing but when the user is moving counter-clockwise. The sum of these two arcs indicates the portion of the scene that the user has viewed.

image


To implement this there are two technical problems: (1) the initial heading might be any number in [0, 360] and this would cause a lot of special cases. (2) the events are given in discrete time points and therefore it is not very easy to detect if the user just moved 10° in clockwise or 350° counter-clockwise. To fix the first problem I transfer all the angles in function `_transformAngle` and then simply assume the initial heading is always 0. And to fix the second problem I define a variable `EPS` and use it to detect the direction.

**Comment by manaswis** [comment]
Was testing it. Not able to reproduce it. Will talk to you in lab.

**Comment by jonfroehlich** [comment]
@manaswis, not able to reproduce what?

**Comment by manaswis** [comment]
The error first and then seeing if the patch resolves it. Will test it again a bit later.

**Comment by manaswis** [comment]
Just tested it. It works perfectly! Let's merge it.

**Pull request merged**
