### PR TITLE
#2861: NSF Funding Info Footer

### LINKED ISSUE #2861: The NSF funding info is incomplete in "We are proudly funded by..."
image

Two things related to the NSF listing:

- The number is not centered below the NSF logo
- We need to have two numbers and both should be hyperlinked: [#1302338](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1302338) and [#2125087](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2125087)

Also relates to: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2732

### PR DESCRIPTION
**Pull request by MohitSoni11**
Resolves #2861 

Before English and Spanish Version:
image

After English Version:
image

After Spanish Version:
image

Changes Made:
1. Centered Text under NSF Logo (took care of mobile representations of website as well)
2. Added #2125087 with hyperlink
3. Added Spanish translation for text

Side-effects: None

### CODE REVIEW

**Comment by misaugstad** [comment]
Thank you! Just a couple things:
1. Can you make them side by side instead of on top of each other? I think it's best to not add any more height to the footer
2. Can you make it so that the hyperlinks automatically open in a new tab?
3. Can you add a Dutch translation as well? Google Translate is fine for something small like this. When we add translations for only some of the supported languages, it just shows the key you used for the translation instead of any of the available translations. So this is what your PR looks like in Dutch.
   Screenshot from 2022-05-25 12-32-30

**Comment by MohitSoni11** [comment]
New Caption Format:
image

Hyperlinks now open in new tab

Dutch Translation:
image

**Comment by MohitSoni11** [comment]
Now the caption is displayed with 2 lines in mobile format and different languages...

Spanish: 
image

Dutch:
image

**Review by misaugstad — APPROVED** [review]
Looking good, thanks @MohitSoni11 !!

**Pull request merged**
