### PR TITLE
#916 renamed all instances of faq to help

### LINKED ISSUE #916: Rename FAQ to Help or something on those lines
Related to #915.

We should consider renaming "FAQ" to "Labeling Guide" or some variation with the word "Guide" in it? My gut feeling is that having the word "guide" might encourage people to look at the FAQ page more.

### PR DESCRIPTION
**Pull request by maubinle**
Resolves #916.

I renamed all instances of "FAQ" to "Help". To test, validate that only "Help" is surfaced throughout the website, including in all links to the page. The only thing I couldn't change were the YouTube video titles, which all explicitly start with "FAQ -". Probably worth fixing them at some point to match.

### CODE REVIEW

**Comment by misaugstad** [comment]
The site works well!

However, you need to change the following line in the .gitignore:
`public/javascripts/FAQ/build/*`.

This resulted in you including a build file in your PR. So you just need to change that line in the .gitignore, probably rerun grunt, and commit the changes so that build file is removed. Then you should be good!

**Comment by maubinle** [comment]
Ah, makes sense, thanks for the review. I'll do this tonight. Cheers!

**Comment by maubinle** [comment]
ok! gitignore file has been changed, cheers for catching that one! hopefully all is good now :)

**Comment by misaugstad** [comment]
@maubinle you updated the .gitignore but you had committed the build file before and left it in there. You still need to remove the build file from your PR. I think `git rm` is the right command for that.

**Comment by maubinle** [comment]
oh no, I'm sorry :( 

I removed it from my end, but to be honest since I removed it in my local branch "git diff" is not showing any changes at all since my last push, and even when I look through the branch (on the Github UI on the Web), there is no FAQ build file. You are talking about the public/javascripts/FAQ directory right? If so, I can try to push the change again, but it seems like nothing has changed since my last push. Very possibly I'm doing something wrong here... just not sure what that is.

**Comment by misaugstad** [comment]
>You are talking about the public/javascripts/FAQ directory right?

The exact file that shouldn't be there is public/javascripts/Help/build/Help.js

**Comment by maubinle** [comment]
ok, done! let me know if there are other changes to be made or if I missed something; if so, let's sync up on Slack so I can make sure to do it right this time.

**Comment by misaugstad** [comment]
@maubinle thank you, it all checks out now!@

**Pull request merged**
