### PR TITLE
Resolve 1054: Mission completion popup showing 0 labels placed

### LINKED ISSUE #1054: Mission Complete Label Counts All Zero in Turk Branch?
image

### PR DESCRIPTION
**Pull request by maddalihanumateja**
Resolves #1054 . The mission completion popup stats were being updated after the next route and mission were loaded. This caused the stats to get reset to zero and show up as such. 

To test this just audit any random condition and place some number of labels. The label count on the mission completion popup should be the same as the number and type of labels you actually placed.

Also verify that the HIT submission button text is now "You're all done! Submit HIT!"

### CODE REVIEW

**Comment by maddalihanumateja** [comment]
Ok @misaugstad . You can test this PR now. I'm confident that it has solved the issue.

**Comment by misaugstad** [comment]
I audited condition 77. In the first 2 missions, the label counts were correct. In the final, 2000ft mission, the label counts were all 0. I had placed 5 of each label type in this last mission, didn't refresh the page at any point, just kept auditing as I had done through the first 2 missions.

 
stillzero

**Comment by maddalihanumateja** [comment]
Yeah. I think I know why this is happening and that it's probably happening for all the last missions. Hang in there with me, just one more iteration.

**Comment by misaugstad** [comment]
I am hanging in here. But please please please rigorously test in the future before asking others to review PRs :pensive:

**Comment by maddalihanumateja** [comment]
Tested the more recent commits on maybe 7 or 8 conditionIds and all the way through till the end of the final mission.

**Comment by misaugstad** [comment]
It has been a long journey. Well done.

**Pull request merged**
