### PR TITLE
Resolves #865: Add returning to mission message

### LINKED ISSUE #865: Need a "Returning you to this mission" message when returning user to in-progress mission
For example, when a user retakes the tutorial they're returned to their current mission progress as of PR #824 . They're shown the mission beginning dialog when they're in the middle of a mission. This should be changed to a different dialog along the lines of "We're returning you to this mission..."

### PR DESCRIPTION
**Pull request by lstrobel**
Resolves #865 

MVP for a modal screen that informs the user that they are returning to an active mission. Simple design as discussed in #865. Will start an issue for potential improvement down the line.

To test, ensure that the modal appears correctly formatted (as defined in the #865 discussion) when returning to active missions as a turker, anonymous, and logged in user. Also, check to make sure that the first mission and start modals remain the same. I tested these conditions on Chrome and Firefox successfully.

### CODE REVIEW

**Comment by lstrobel** [comment]
Here is an image of the current screen:
screenshot_2018-12-31 project sidewalk

**Comment by lstrobel** [comment]
New image after some feedback: 
screenshot_2018-12-31 project sidewalk

**Comment by jonfroehlich** [comment]
Thanks. Looking better. Needs like 20-30 more pixels of vertical spacing above button. Play around and choose a good value.

**Comment by lstrobel** [comment]
Added some space:

annotation 2019-01-08 143128

**Comment by jonfroehlich** [comment]
Looks good! (Maybe add an exclamation mark in the button?)

**Comment by misaugstad** [comment]
Tested it and it looks good! Just add the "!" and I'll merge!

**Pull request merged**
