### PR TITLE
[WIP] updated libraries and code changes

### PR DESCRIPTION
**Pull request by athersharif**
this is a wip pr. too much noise due to auto-styling changes. not ready for review yet but feel free to play with it.

### CODE REVIEW

**Comment by misaugstad** [comment]
Oh no what happened with the style changes :sweat_smile: :sweat_smile:

**Comment by misaugstad** [comment]
And does it compile right now?

**Comment by athersharif** [comment]
no clue, may have been my editor lol. really didn't want the styling changes there haha.

nope, not yet. started with 2000 errors, down to 1680. but i think i know the code changes needed for migration. some of these errors are also `unused import`s and `unused val`s which i don't think the previous version complained about when compiling.

**Comment by athersharif** [comment]
look at the changes in AuditController tho (https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1406/files#diff-8932b9b74210fd7a8892d2c1ea80fc2eR3). down to 0 errors on that controller. so basically we'd need to apply the same kinda changes in other controllers. but that needs a thorough check that everything works. do we have a reliable test suite?

**Pull request closed without merging**
