### PR TITLE
#2680 add uic logo

### LINKED ISSUE #2680: Add UIC logo to Project Sidewalk website
Talked to Yochai about Project Sidewalk Chicago. We should add in UIC logo. Yochai is going to send us logos.

image

### PR DESCRIPTION
**Pull request by ishaanp9**
Resolves #2680
- Added png image of UIC logo (higher res, smaller res looked very pixelated) to landing page.
- Changed the padding css for the container-image from the right and left to be 5% of total screen size to make it more dynamic.

To test changes:
- See if it looks fine, and try on different screen sizes.

This is a brief description of the problem solved or feature implemented and how you implemented it.

##### Before/After screenshots (if applicable)

Before:
Capture
After:
Capture1

##### Testing instructions
1. See if it looks fine, and try on different screen sizes.

##### Things to check before submitting the PR 
- [ ] I've written a descriptive PR title.
- [ ] I've added/updated comments for large or confusing blocks of code.
- [ ] I've included before/after screenshots above.
- [ ] I've asked for and included translations for any user facing text that was added or modified.
- [ ] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if you need to update the logging), ask Mikey. Then make sure the documentation on [this wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events) is up to date for the logs you added/updated.
- [ ] I've tested on mobile (only needed for validation page).

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Thanks for including the screenshot and for your work on this.

I don't think we should just use a 3269x1282 pixel image unless we have to—especially when we downsample it to a much smaller area for the landing page. It just wastes bandwidth and increases loading time.

So, I added two other smaller options for you to choose from here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2680#issuecomment-974124382. Please experiment and update this PR appropriately.

**Comment by ishaanp9** [comment]
Ok, I was able to use the 42kb version and it should look the exact same as the screenshot I had posted in the first pr.
Capture

**Comment by jonfroehlich** [comment]
Thanks!

**Review by misaugstad — APPROVED** [review]
Looks great, thanks @ishaanp9 !!

**Pull request merged**
