### PR TITLE
fixed  onboarding so that intersection is not obscured by instructions

### LINKED ISSUE #1260: Onboarding: intersection obscured by instructions
I've noticed that on the corner with the missing curb ramp, the missing curb ramp can be obscured by the instructions on how to rate severity, see image below:

obscured_missing_ramp

This is only a problem at this particular corner. It could be pretty easily solved by requiring the user to pan a little bit further before they can label.

Easy, unimportant fix.

### PR DESCRIPTION
**Pull request by ShivenBhatt**
Fixes #1260 
Fixes the problem where the instructions obscured the curb ramp by making the user pan left a bit more. Looks like this:
image

### CODE REVIEW

**Comment by misaugstad** [comment]
Thanks! I will test out the fix in the next few days! Could you just update the title of the PR so it doesn't just end with "..."? :grin:

**Comment by ShivenBhatt** [comment]
Oops. Fixed.

**Comment by ShivenBhatt** [comment]
oops. Fixed.

**Comment by misaugstad** [comment]
@ShivenBhatt Users are now able to pan too far so that the curb ramp is not visible at all when they are asked to label it.

pan-too-far-tutorial

This is definitely something that needed to be checked before submitting a PR for someone else to review. This seems like the number one thing to check: if you fixed the problem of not being able to pan far enough, the first thing you would check is if they can now pan too far. 

Before submitting PRs in the future, just make sure to try and think through how someone might test your code, then do that testing yourself to catch anything ahead of time :relaxed: Making that time investment up front ends up saving you (and me) quite a bit of time, plus the fix gets merged faster :wink:

**Comment by ShivenBhatt** [comment]
sorry about that. User can only pan to here now:
image
here's the minimum pan:
image

**Comment by misaugstad** [comment]
Okay thanks, works well now! Merging :)

**Pull request merged**
