### PR TITLE
756 log clicks for start mapping

### PR DESCRIPTION
**Pull request by adash12**
Fixes 756 - adds logging for clicking "Start Mapping" in navbar and index page. Logs are of the form `Click_module=StartMapping_location=Navbar` and `Click_module=StartMapping_location=Index`.

### CODE REVIEW

**Comment by manaswis** [comment]
I think `Click_Module` should be renamed to `ClickModule`. Then for doing analysis, we can get the key-value pairs by splitting the string using `_` as the delimiter. Note: I don't know how everything else is being logged but I feel that's how we should do it. @misaugstad What do you think?

**Comment by misaugstad** [comment]
@adash12  When testing out this branch, Click_module=SignIn and Click_module=StartMapping_location=Navbar are not being logged when clicking on the buttons on the navbar. The other StartMapping button is being logged correctly, though.

**Comment by misaugstad** [comment]
@manaswis The first thing is an action, then the remainder are key-value pairs, delimited by the underscore, as you said. So it is saying you "click", then the module=something, etc etc.

@adash12 was starting with "click" a design decision that was based on how stuff was previously being logged or something? Why are we starting with something that isn't part of a key-value pair?

**Comment by adash12** [comment]
@misaugstad Yes, I had begun to start these logs with click before our discussion about naming using key-value pairs. 
Also, will look into the navbar not logging.

**Comment by manaswis** [comment]
>  The first thing is an action, then the remainder are key-value pairs, delimited by the underscore, as you said. So it is saying you "click", then the module=something, etc etc.

Ah, I see. This makes sense.

**Comment by adash12** [comment]
@misaugstad Clicking "Start Mapping" in the navbar logged properly for me, however Sign In did not so I fixed that

**Comment by misaugstad** [comment]
They are both now working for me :+1:

**Pull request merged**
