### PR TITLE
Resolves #853 - Tutorial Text Changed For Incorrect Severity

### LINKED ISSUE #853: Tutorial: when getting severity wrong, they should be told why
In the tutorial, if a user gets the severity rating wrong for a label, the explanation of why the label should have been at that severity is not given when we tell them that they were wrong...

sidewalk-missing-ramp1
sidewalk-missing-ramp2

In a user test, they didn't really read the text where it says that it is only a 3 since there is a curb ramp next to it and gave it a 5. Then it just says it has severity '3' and they were really confused, since a the curb ramp is missing, how could it be a 3?

I think the text should be modified
Hmmm, this is a slightly sever problem since it is next to an existing curb ramp. ...

### PR DESCRIPTION
**Pull request by sarahsmo**
Resolves Issue #853 
When completing the tutorial, if you marked a ramp with the incorrect severity level, text would show up asking you to change the severity level. I have added more information to this text so that the user knows why their marked level was incorrect. 

Before: 
image

After:
image

### CODE REVIEW

**Comment by manaswis** [comment]
Adding screenshot for the missing curb ramp for severity 3:

image

**Comment by manaswis** [comment]
I don't like the text for this one.

I think it should be: 

Hmm, this is a slightly severe problem since it is next to an existing curb ramp. Let's click "3" to change the severity of the missing curb ramp.

Any comments @misaugstad @jonfroehlich?

Relatedly, should we even make these changes now because we would want to resolve #1103 i.e. changing the severity of the features/issues based on ADA guidelines. That will lead to further changes.

**Comment by misaugstad** [comment]
>Relatedly, should we even make these changes now because we would want to resolve #1103 i.e. changing the severity of the features/issues based on ADA guidelines. That will lead to further changes.

That was my plan.

**Comment by sarahsmo** [comment]
Let me know if there is something that you need me to do with this, not totally sure what direction you are trying to go in.

**Comment by manaswis** [comment]
@misaugstad 
> That was my plan.

What was the plan? Have these changes made or wait for the PR for issue #1103?

**Comment by misaugstad** [comment]
Wait for that PR, or even just do them together since they are highly related.

**Comment by manaswis** [comment]
Okay sounds good! @sarahsmo You can make the small edit I suggested in this PR.

**Comment by sarahsmo** [comment]
Will do @manaswis

**Comment by manaswis** [comment]
@misaugstad On second thought, I will push these changes once @sarahsmo makes the edit. We can look into #1103 when we get to it.

**Comment by sarahsmo** [comment]
@manaswis I have changed it as per your request. 

Before: 
image

After:
image

**Comment by manaswis** [comment]
I was testing this again and I am having second thoughts about the text. It's still not great. I am postponing the merge of this PR until #1103 is resolved.

**Comment by sarahsmo** [comment]
Ok, sounds good!  Let me know if there is anything else you need me to change. @manaswis

**Comment by misaugstad** [comment]
>I am postponing the merge of this PR until #1103 is resolved.

Since the text will likely change after we make the changes from #1103 anyway, and since we haven't decided on the correct text anyway, I'm going to close this PR. The text we choose should be debated in an issue thread before we submit a new PR.

**Pull request closed without merging**
