### PR TITLE
Added non-null constraint to temporary_label_id

### LINKED ISSUE #2133: temporary_label_id stored as Option[Int] in Database
As described in the title, temporary_label_ids (which are used to locate labelId in the database upon form submission, for example) are stored as Option[Int], which seems strange considering how it is needed to identify if a label already exists in the database

### PR DESCRIPTION
**Pull request by dylanbun**
Resolves #2133 

Changed the temporary_label_id column in the label and audit task interaction table to be from null to non-null.

- [X] I've written a descriptive PR title.

### CODE REVIEW

**Comment by misaugstad** [comment]
Ahh, so we actually only wanted to change this for the `label` table. Not all interactions in the `audit_task_interaction` table are tied to a label, so it should be an option type there. And I don't believe that there are any instances where it _is_ null in the `label` table. I'm okay with the check there just in case; could you just add a comment to say that there are no instances of this in the live databases at the time it was run?

**Comment by dylanbun** [comment]
yup, updated it. ready for review!

**Review by misaugstad — CHANGES_REQUESTED** [review]
Oh you still need to update the `Label` Scala class to use an `Int` instead of `Option[Int]`!

And since you're already making an update, making the comment in the SQL file match the style would be nice :)

**Comment by dylanbun** [comment]
ready for review (assuming you just wanted a period added to the sql file).

**Comment by misaugstad** [comment]
And starting with a capital letter, but I can change that if everything else checks out ;)

**Review by misaugstad — APPROVED** [review]
Great, thanks @dylanbun!!

**Pull request merged**
