### PR TITLE
Partially resolves 1384: validation initial ui bug fixes

### PR DESCRIPTION
**Pull request by aileenzeng**
Fixes some initial bugs from #1384:
* Update progress in the beginning to prevent initial label being loaded twice
* Updated wording so "an" is changed to "a" for missing sidewalks. ("Is this an missing sidewalk" --> "Is this a missing sidewalk?")

Before: 
image

After:
image

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Can you make the question text bigger with more vertical spacing beneath it? Margin-bottom like 10 or 15px?

**Comment by aileenzeng** [comment]
Sure! How are these?

image

image

**Comment by aileenzeng** [comment]
Two more: 
(top 27px, font size 29)
image

(top 30px, font size 29)
image

**Comment by jonfroehlich** [comment]
Either of these look good. Pick one. :)

**Comment by misaugstad** [comment]
Just tested and it all looks good!

**Pull request merged**
