### PR TITLE
Resolves #1167 Adds  pay-rate column to the mission_user table

### LINKED ISSUE #1167: user_mission table needs to be updated to indicate the pay rate that was used for turkers' missions
This will be useful when calculating descriptive stats for pay rate per mile (or some fixed distance) and pay rate per turker. For example, we paid turkers an average of $230.12 (SD=XX).

### PR DESCRIPTION
**Pull request by maddalihanumateja**
Resolves #1167

1. Log into a volunteer account and complete a mission. You should see a new record in the mission_user table with pay__per_mile set to 0.0

image

2. Access a turker account using the mturk referrer (for example: http://localhost:9000/?referrer=mturk&hitId=test7&workerId=some_turker_name&assignmentId=test7). Complete a mission. You should see a new record in the mission_user table with pay_per_mile set to turkerRewardPerMile=4.17.

image

The pay rate is stored in the turkerRewardPerMile value in the mission controller. Vary it and try 1. and 2. again.

### CODE REVIEW

**Comment by misaugstad** [comment]
How are you dealing with turkers that have already completed missions? How are we filling those in?

And I think you may have branched off of my branch `870-completion-not-reaching-100` for PR #884 instead of develop? If so, I guess we can wait until #884 is merged before looking at this one.

**Comment by maddalihanumateja** [comment]
>@maddalihanumateja How are you dealing with turkers that have already completed missions? How are we filling those in?

I'll manually run an update command.

>And I think you may have branched off of my branch 870-completion-not-reaching-100 for PR #884 instead of develop? If so, I guess we can wait until #884 is merged before looking at this one.

How did you determine this? I started working on this branch before `870-completion-not-reaching-100` so I think there is a low probability of it happening.

**Comment by misaugstad** [comment]
>I'll manually run an update command.

Alright.

>How did you determine this? I started working on this branch before 870-completion-not-reaching-100 so I think there is a low probability of it happening.

I think you know how ;) You fixed by changing base from master to develop. It had just said 12 files changed, and a bunch of the changes were code that I had written recently. You're all good now.

**Comment by maddalihanumateja** [comment]
Ok I've included the changes that you've made and changed turkerRewardPer mile to payPerMile.

**Pull request merged**
