### PR TITLE
Mission Complete Emoji

### PR DESCRIPTION
**Pull request by danZzyy**
We now have a selection of smiley faces to make the completion message less serious.

### CODE REVIEW

**Comment by danZzyy** [comment]
image

**Comment by jonfroehlich** [comment]
Can you paste in some screenshots of what this looks like? Also, are these smiley faces randomly selected to follow the text?

**Comment by danZzyy** [comment]
The smileys are randomly selected from :D, :) , and :-) and appended to the text. My second comment is a screenshot of the message.

**Comment by jonfroehlich** [comment]
I actually meant to use emoji icons like:
- https://thenounproject.com/term/smile/501843/
- https://thenounproject.com/term/wink/407485/

(though they should all have a consistent look-and-feel)

:D, :), and :-) are too tech'y imo and not accessible enough for a general audience.

**Comment by danZzyy** [comment]
Oh ok. I know they exist in unicode but I was hesitant because I wasn't sure if it might cause problems. Or did you mean using an image or svg?

**Comment by jonfroehlich** [comment]
Image or svg.

**Pull request merged**
