### PR TITLE
Admin map selectors

### LINKED ISSUE #182: Admin Interface: Select Label Types To Show on Map
It would be interesting and useful to be able to select which label types to show in the admin interface map that visualizes all collected data. For example, if I wanted to see all missing curb ramp labels, I could deselect the other label types. As now, it's very difficult to see this information.

image

### PR DESCRIPTION
**Pull request by tongning**
This should resolve #182. It seems that map panning is smoother when items are deselected, but since all are checked by default the page load time remains the same.

### CODE REVIEW

**Comment by Soben713** [comment]
Interesting. Thanks, @tongning.

I'm working on the admin map as well, I'll look into this after I'm done and merge it to make sure there are no conflicts.

**Comment by jonfroehlich** [comment]
This is great Anthony. Can you include some screenshots?

**Comment by tongning** [comment]
Here's what it looks like with everything enabled (default view):
all-checked

And with some marker types unchecked:
some-unchecked

**Comment by Soben713** [comment]
This pull request has some conflicts with the master branch. @tongning Do you want to resolve them first before I review it?

**Comment by tongning** [comment]
Yeah sure - I'm a bit busy today but I'll look at it later this week.

**Comment by Soben713** [comment]
Great, thanks.

**Comment by tongning** [comment]
I'll close this pull request and submit a new one later that implements #386.

**Comment by jonfroehlich** [comment]
@tongning actually, i'd prefer to see the checkbox implementation first (i.e., pushed to production). you can then work on the slider bar.

**Pull request closed without merging**
