### PR TITLE
2332-Leaderboard-Alignment

### LINKED ISSUE #2332: Side-by-side overall + weekly leaderboard not properly aligned
Ideally, these leaderboard tables need to be perfectly vertically aligned to allow side-by-side comparison. They are not currently because the "Overall" side has subtitle text that the "weekly" does not. The easy solution to this would be to put text beneath "Weekly" (about how weekly is calculated such as "Weekly results reset every Sunday at 12am Pacific")

image

### PR DESCRIPTION
**Pull request by jacknussbaum**
Resolves #2332 

Fixes alignment issues between the overall and weekly leaderboard, adds a heading to the weekly leaderboard.

Before:
image

After:
image

### CODE REVIEW

**Comment by jacknussbaum** [comment]
Merge conflicts corrected.

**Comment by jacknussbaum** [comment]
Oops.. will fix this PR. Accidentally included the old main.css. My bad

**Comment by misaugstad** [comment]
The leaderboards aren't aligned anymore. I suspect that maybe this was caused by the merge with develop? But here's what it's looking like for me:
Screenshot from 2020-11-18 13-13-05

**Comment by jacknussbaum** [comment]
Should be fixed now!

**Review by misaugstad — APPROVED** [review]
Looks good! I wanted to get this out tonight so I made a quick change myself: I changed `leaderboard.detail.overall` to `leaderboard.overall.detail` and `leaderboard.detail.weekly` to `leaderboard.weekly.detail` to fit the style we already had in `leaderboard.overall.title`.

**Pull request merged**
