### PR TITLE
Disabled labeling buttons on survey display

### LINKED ISSUE #1091: Keyboard shortcuts should be disabled when the survey pop-up is shown
Currently, if any of the shortcuts such as 'c', 's', 'o' etc. are used in the free form text or otherwise, the label is pre-selected (in case of label shortcuts) when the next mission loads. That should not happen. All interactions with the tool in the background should be disabled.

image

### PR DESCRIPTION
**Pull request by maddalihanumateja**
Resolves #1091 . Complete the first 2 missions to display the survey. Try pressing labeling keyboard shortcuts and check that the label buttons don't get selected.

Please remember to check that the browser has reloaded svlabel.js or try this in incognito mode

### CODE REVIEW

**Comment by manaswis** [comment]
The labeling buttons are no longer are selected. So that works!

However, the zoom in/out are still activated. So if you use `Z` or `Shift + Z` then the tool is zoomed in when you dismiss the survey.

**Comment by manaswis** [comment]
I think I know why the disableInteractions() didn't disable keyboard shortcuts.

Did you add svl.keyboard.setStatus('focusOnTextField', true); when the textbox focus event happens? Check ContextMenu.js file for more details.

**Comment by maddalihanumateja** [comment]
Zooming should be disabled now

**Comment by manaswis** [comment]
Works! There is a super minor issue of the zoom button being greyed out after filling out the survey. But it works when the mouse enters the GSV screen area.

**Pull request merged**
