### PR TITLE
#1044 Changed - difficult region overlay centered

### LINKED ISSUE #1044: Keep difficult region overlay centered
As mentioned in PR #1011 the overlay that says that you are going to audit a difficult region can be off-center, depending on the resolution of your monitor and zoom level. This should really be centered independent of those two variables. Here is an example of the worst-case:

off-center-overlay

An example of a "difficult" region is monumental core (which is the largest region when you look at one of our choropleths.

### PR DESCRIPTION
**Pull request by sarahsmo**
Removed the margin top and left because it was a fixed position.

Added margin: auto to keep the overlay centered at all times. 

Resolves #1044

### CODE REVIEW

**Comment by manaswis** [comment]
@sarahsmo There are some issues in running this branch. It says they have diverged.

**Comment by sarahsmo** [comment]
@manaswis yeah, I am having some problems with the branches, I am not very good with this github stuff yet

**Comment by sarahsmo** [comment]
@manaswis I am kinda stuck with what to do, sorry I am bad at github

**Comment by manaswis** [comment]
Simplest is create another branch for this issue, make your changes there and delete this branch.

**Comment by sarahsmo** [comment]
@manaswis I've tried that but I am having issues with my develop branch: 
image

**Comment by manaswis** [comment]
Do a git stash on your local computer.

**Comment by sarahsmo** [comment]
So I deleted the branch, did a git stash, recreated the branch, checked the code and it still had my changes. I don't know what else to do.
image

**Comment by misaugstad** [comment]
git reset --hard origin develop
in your develop branch

**Comment by sarahsmo** [comment]
@manaswis I deleted the branch, did the reset, created it again, edited the code, committed changes, and then tried to push but this happens:
image

**Comment by misaugstad** [comment]
Ahh I see. You only deleted your branch locally; you also need to delete it on github.

So after doing your `git branch -D 1044-difficult-region-overlay-center` run `git push -d origin 1044-difficult-region-overlay-center` to delete it from github as well.

**Pull request closed without merging**
