### PR TITLE
Adds German language

### LINKED ISSUE #3219: Request for German language
From our Zurich partners:

> We have started the recruitment phase for data collection. The majority of our participants are/will be German speaking. Is it possible to add German to the language list of the Project Sidewalk tool? 😬 As of May, I will have a research assistant who can help translate if needed.

### PR DESCRIPTION
**Pull request by misaugstad**
Resolves #3219 

Adds German language translations to the website. I finally made some much needed CSS fixes that help out with how Dutch and Spanish translations look as well.

##### Before/After screenshots
Here are just a few pics of what it looks like!
Screenshot from 2023-06-15 11-43-39
Screenshot from 2023-06-15 11-43-09
Screenshot from 2023-06-15 11-42-59
Screenshot from 2023-06-15 11-42-44

##### Things to check before submitting the PR 

- [x] I've written a descriptive PR title. 
- [x] I've included before/after screenshots above.
- [x] I've asked for and included translations for any user facing text that was added or modified.
- [x] I've tested on mobile (only needed for validation page).

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Overall, looks great. Can I make one suggestion? I recall seeing a recent GitHub Issue posting about this too but the spacing on this is off.

Can we be more intelligent with the CSS to reduce the vertical spacing underneath **Richtige Beschriftung** by pushing the context text (Bewerten mit Einverstanden) upwards. This also has the benefit of having a better margin with the surrounding outline.

image

**Comment by jonfroehlich** [comment]
Put in the fix mock here: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/3257

**Comment by misaugstad** [comment]
Thank you! I didn't consider it a dealbreaker to get the German translations out there, but it was definitely important enough to warrant creating an issue. And I want to get an intern working on it very soon!

**Comment by jonfroehlich** [comment]
Nice. Sounds good. It is the kind of thing that might require a bit of CSS cleverness because it is content dependent.

**Comment by jonfroehlich** [comment]
And hopefully my mocks will make the intern work more straightforward

**Pull request merged**
