### PR TITLE
Change how roles are implemented

### LINKED ISSUE #836: Change how user roles are implemented
For Administrator and Researcher roles, multiple entries are in the user_role table, one for each role that they have. So if you are just a researcher, you have a User entry and a Researcher entry. If you are an Administrator, you have all 3. I can't think of a scenario wherein this is intuitive and/or useful.

We should consider changing this so that if you become an admin, your role is updated from User to Administrator, instead of adding a new role.

### PR DESCRIPTION
**Pull request by adash12**
Resolves #836 : Replaces old system of user roles (users have multiple roles) with a hierarchy of roles:
1 - User (no special permissions)
2 - Researcher (has no special permissions but can be excluded from admin charts)
3 - Admin (has special permissions, i.e. accessing admin page)
4 - Owner (has permissions of admin but cannot have role changed by admins when that feature is implemented)

Removes hard-coded list of researchers in `UserRoleTable.scala` and replaces with checks to the actual table.

### CODE REVIEW

**Comment by adash12** [comment]
Will also do #837 in this PR

**Comment by adash12** [comment]
Added little dropdowns on the User Table on the Admin page that change users' roles. Ready to be tested.

**Comment by misaugstad** [comment]
So I updated this PR to reflect the addition of the turker role. It works really well, nice job @adash12 !!

The only thing I found is that once you change someone's role, then try to resort the list of users on the admin page by role, it sorts the user by their old role until you refresh the admin page. Their role is updated in the backend. I don't think this is worth the time to fix, considering how infrequently we will be changing roles anyway. Therefore, I am merging this PR!

@manaswis this is something that should definitely be specifically tested on dev, since it makes changes to the database; we should be careful :slightly_smiling_face:

**Comment by manaswis** [comment]
Thanks @misaugstad!

> The only thing I found is that once you change someone's role, then try to resort the list of users on the admin page by role, it sorts the user by their old role until you refresh the admin page. Their role is updated in the backend. I don't think this is worth the time to fix, considering how infrequently we will be changing roles anyway. Therefore, I am merging this PR!

Could you create an issue for it? Just so it's recorded.

**Comment by misaugstad** [comment]
Done, #1151

**Pull request merged**
