### PR TITLE
285 Login during mission without page refresh

### LINKED ISSUE #285: Creating account in the middle of a mission bounces user back to a new mission
**UPDATE (Jun 28, 2017)**: Editing the issue for starting a new mission when you newly sign up. Updated according to the [latest comment](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/285#issuecomment-310861272) in this thread. 

When the user gets the "contributing a lot" message asking them to sign up, the next mission they get is a new mission. This creates confusion for the user that all his progress made as an anonymous user was lost, and at which point they could drop out of the site (as mentioned by 1 user during the relaunch usability testing).

Ideal behavior: Continuing with the same mission and their previous contributions as an anonymous user getting added to their newly created account.

However, this is time-consuming for the relaunch. We need to come with some temp fixes that removes the user confusion that leads to a drop-out.

**Original Issue Text (Sep 1, 2016)**:
This would have happened when the user was labeling as an anonymous user and was requested to create an account when he labeled a good amount.

bouncing_back_to_beginning

Is it a bug?

### PR DESCRIPTION
**Pull request by sbower213**
Resolves #285.

Asynchronous sign in allows users to sign into their account and continue on the mission they were working on. There are a few minor issues with this (will open new issues shortly) but this functionality should be sufficient enough for relaunch.

### CODE REVIEW

**Comment by maddalihanumateja** [comment]
The asynchronous sign in works as you say it does. I'm not sure if I'm the only one facing this issue but once I login 
 - the cursor changes to a four headed arrow
 - panning on both mouse and keyboard gets disabled. I can only use the clickable street view navigation arrows to move around
 - I also run into a blank panorama after a while

image

This happens inconsistently so I need another pair of eyes for confirmation. I'm running your branch on Windows and using Chrome.

**Comment by sagec108** [comment]
The only issue that I experience as well is the crosshair bug (which I can hopefully resolve in PR #793.

**Comment by maddalihanumateja** [comment]
I find it suspicious that only I'm encountering this bug. It might be that we are testing different scenarios so I want you guys to test this again. 

The bug used to show up for me when I start a new private Chrome session and 
 - signin or signup on the first mission's "You've been contributing a lot" popup
 - signin or signup using the navbar button

What I noticed (using what Sage mentioned in a chat last week) was that this didn't happen for signin when I don't disable interactions during the popup. But it continues to happen for signup.

I think the code for the async signup box should also account for the occurrences of the disableInteractions() function.

In the event we decide that what is happening on my computer is an isolated case I'll consider merging this request.

**Comment by sbower213** [comment]
@maddalihanumateja can you post a screenshot of your js console when you get this error? i remember it threw a ton of errors when you showed this to me last week, maybe we can try and find the root cause based on what throws those errors. i still can't reproduce this error on my machine.

**Comment by maddalihanumateja** [comment]
Now that sage and manaswi have also checked this it seems we do have issues. My issue of being unable to pan after signup or signin seems to be related to having underscores in my username. This is also a keyboard shortcut for zooming out and brings up errors similar to #678 (Going to create a new issue for this). I'm going to go ahead and merge this pull request since the original requirement of asynchronous signup/signin has been implemented.

**Pull request merged**
