### PR TITLE
Modified code for HIT approval and bonus approval

### PR DESCRIPTION
**Pull request by maddalihanumateja**
Make sure the approve_hits variable in hit_approve_assignments.py file and send_bonuses variable in hit_approve_bonus.py file have been set to False before starting. More instructions forthcoming.

### CODE REVIEW

**Comment by manaswis** [comment]
I am gonna wait for your instructions (as you have mentioned in the PR) before starting to test this PR.

**Comment by misaugstad** [comment]
@maddalihanumateja what do you think should be done with this PR?

**Comment by maddalihanumateja** [comment]
@misaugstad I've mentioned in our recent discussion that the code that was going to be tested in this PR needs to be modified.
1. I had left space for implementing the quality indicator that would allow me to reject HITs or low quality. Right now this code just accepts everything which isn't the desired behavior.
2. The bonuses greater than $100 had to be split up into multiple payments scheduled over some days. The PR was created before this we realized this fact. I hadn't changed the code to allow the split bonus payment method.

You can discard this PR for now.

**Comment by misaugstad** [comment]
This PR needs to be redone with a bunch of changes. I linked to this PR from the relevant issue (#1063 ) so we can find this branch if necessary. But I'm going to close this PR; we will start these updates from scratch later this summer.

**Pull request closed without merging**
