### PR TITLE
Add twitter card meta tags

### PR DESCRIPTION
**Pull request by Soben713**
Issue: #272.

Note: this could only be tested after being deployed. I am merging it to the master to test it after the next deployment (it is just 4 lines of HTML meta tags copied from twitter docs).

### CODE REVIEW

**Comment by jonfroehlich** [comment]
We can test on a dummy twitter account.

**Comment by Soben713** [comment]
@jonfroehlich The tags are added to the HTML of our landing page. It is not related to any twitter account.

**Comment by jonfroehlich** [comment]
I know. My suggestion still applies

**Comment by Soben713** [comment]
@jonfroehlich Can you explain it? The code has to be deployed somewhere, otherwise, twitter cannot crawl it.

**Comment by jonfroehlich** [comment]
Exactly. Once we deploy, we can test that the card works by tweeting on dummy account. 

Also, could certainly test by deploying this part of html to any dummy webpage--even something off of cs.umd.edu/~jonf/

**Comment by Soben713** [comment]
Right. I am going to deploy and test it tonight. So it is fine.

**Pull request merged**
