### PR TITLE
Resolves 1477: Parameterized import dump script

### PR DESCRIPTION
**Pull request by athersharif**
resolves https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1477.

couple of notes:

- ~feel free to change the name of the default db from `dump` to something more meaningful.~ (file to be named at `[database-dump]`, updated the readme in https://github.com/ProjectSidewalk/SidewalkWebpage/commit/5878647611cfa76e91cd9fc8a08164105f4b28a1)
- ~used `dumpdb` as the parameter, feel free to change that as well.~ (changed to `db` in https://github.com/ProjectSidewalk/SidewalkWebpage/commit/5878647611cfa76e91cd9fc8a08164105f4b28a1)
- ~will also need a slight change to the readme file once the naming convention of the dump files is finalized.~ (addressed in https://github.com/ProjectSidewalk/SidewalkWebpage/commit/5878647611cfa76e91cd9fc8a08164105f4b28a1)
- may or may not want to check in the schema files.

after the above, this should be good to go.

### CODE REVIEW

**Comment by misaugstad** [comment]
@athersharif it looks like you just parameterized the name of the dump file here. I was looking for parameterizing the name of the database.

**Comment by athersharif** [comment]
@misaugstad think you may have gotten confused by https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1494/files#diff-b67911656ef5d18c4ae36cb6741b7965R3 there. that sets the default to `dump`. the way it works is to do `make import-dump dumpdb=blah` which will look for the `blah` file in the `db` directory (where we placed `dump`). if no parameter is provided, it defaults to `dump`.

(sorry, this should have been in the description).

**Comment by misaugstad** [comment]
@athersharif right, but then it will use the dump file named `blah` to create a database called `sidewalk`. I want to be able to take a dump file and make multiple different databases with it. Something like `make import-dump dbname=sidewalk-newberg`, `make import-dump dbname=sidewalk-seattle`. So that I can have multiple databases up -- I don't want to erase the old database :grin:

**Comment by athersharif** [comment]
Ah got it. Thought you were going for one db but different versions of it depending on what somebody might be working on but yeah that’d be annoying if you wanted to work on multiple stuff at the same time.

I’ll make the change.

**Comment by athersharif** [comment]
@misaugstad thoughts on https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1494/commits/5878647611cfa76e91cd9fc8a08164105f4b28a1?

**Comment by misaugstad** [comment]
Looks good!  Though I think we want to keep the schema named sidewalk, just want to change the database name. O/w I think this will do it!

**Pull request merged**
