### PR TITLE
1945 Region-specific tags

### LINKED ISSUE #1945: Adding new tags for Mexico City
Should we consider adding new tags or other things for Mexico City? I was walking through the polygon area (from KML) and saw things that would be less common in US cities (e.g., fruit stands that take over sidewalk).

Something to think about...

### PR DESCRIPTION
**Pull request by shokiami**
Resolves #1945 

This PR makes it so that the tags available during auditing depend on the current region's country (USA or Mexico). This PR also updates some of the Spanish translations as well as tag hotkeys. 

@misaugstad Unfortunately, I have not yet tested this PR with a US database (I recently requested access to the google drive Columbus database), but it seems to be working perfectly for SPGG! 
Also, I asked Michael about line 70 of LabelController.scala and we both feel like there is a better way to do that. Please let me know what you think. 

Here are some screenshots of SPGG:

Curb Ramp:
 Add "not level with street" / "con desnivel" to ALL cities.
 Update "estrecha" -> "muy angosta"
 Update "empinada" -> "empinada (mucha pendiente)"
Screen Shot 2020-10-07 at 10 49 04 PM
Screen Shot 2020-10-07 at 11 22 19 PM

Missing Curb Ramp:
 Update "ruta alternativa presente" -> "hay una ruta alternativa segura para cruzar"
 Update "sin ruta alternativa" -> "no hay una ruta alternativa para cruzar"
Screen Shot 2020-10-07 at 10 49 13 PM
Screen Shot 2020-10-07 at 10 53 22 PM

Obstacle:
 Remove "fire hydrant" / "hidrante contra incendio" from MEXICAN cities
 Remove "parked bike" / "bicicleta estacionada" from MEXICAN cities
 Remove "construction" / "construcción" from MEXICAN cities
 Add "garage entrance" / "entrada a cochera" to MEXICAN cities
 Add "stairs" / "escalones" to MEXICAN cities
 Add "street vendor" / "comercio ambulante" to MEXICAN cities
 Add "large step" / "desnivel" to ALL cities
 Update "bote de basura / contenedor de reciclaje" -> "basurero"
 Update "construcción" -> "obra en construcción"
Screen Shot 2020-10-07 at 10 50 15 PM
Screen Shot 2020-10-07 at 10 53 29 PM

Surface Problem:
 Remove "brick" / "ladrillo" from MEXICAN cities
 Remove "construction" / "construcción" from MEXICAN cities
 Add "very broken" / "rota" to ALL cities
 Update "uneven" -> "uneven/slanted"
 Update "con baches" -> "textura irregular"
 Update "césped" -> "hierba"
 Update "banqueta estrecha" -> "muy angosta"
 Update "construcción" -> "obra en construcción"
Screen Shot 2020-10-07 at 10 50 40 PM
Screen Shot 2020-10-07 at 10 53 41 PM

No Sidewalk:
 Add "gravel/dirt road" / "camino de tierra" to ALL cities
 Add "shared pedestrian/car space" / "plataforma única" to ALL cities
Screen Shot 2020-10-07 at 10 50 50 PM
Screen Shot 2020-10-07 at 10 53 49 PM

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Woohoo. Great work @shokiami. I didn't look over the code but have one general comment. Last night during our team meeting, you said that this is adjustable per country rather than per city. I think we might want the precision of the latter. For example, I know that shared bicycling is coming to Mexico City, which means that they will have far more parked bikes on sidewalks. And given that we generally treat everything in Project Sidewalk as a per city construct rather than per country, it makes more sense to my brain to make customization per city as well.

**Comment by misaugstad** [comment]
It will be trivially easy to make it per-city in the future, but it's probably fine as-is for now. Especially if it means getting it merged more quickly

**Comment by shokiami** [comment]
@jonfroehlich Yeah that totally makes sense.
@misaugstad Are you sure you don't want me to make the change? As you mentioned, I can get that done instantly.

**Comment by misaugstad** [comment]
Okay yes, I was thinking I was about to go ahead and review the PR at that time, but now I've got to do a couple other things first, so you've got time to make the change. Thanks @shokiami

**Comment by shokiami** [comment]
@jonfroehlich @misaugstad 
Done!

**Comment by misaugstad** [comment]
@shokiami thank you! I think I also noticed an error in the console whenever I tried to use a keyboard shortcut for a tag that is not in the current city... Could you investigate that and see if you can get rid of the console error? I doubt that it is causing any functional issues, it would just best to not log those errors.

And if you haven't already, could you check the `audit_task_interaction` logs to make sure all the keyboard shortcuts and tag applications are being logged correctly after you changes?

**Comment by shokiami** [comment]
@misaugstad Hmmm interesting... I tested for that before and did not see any error. I tried again just now and was not able to recreate the error. Is there a specific tag that is causing that error? 
Also, I checked the audit interactions table and everything looks good:
Screen Shot 2020-10-08 at 8 58 42 PM

**Comment by shokiami** [comment]
@misaugstad Ohhhhh wait no yeah now I see the errors! I'll fix that right now. 😅

**Comment by shokiami** [comment]
@misaugstad Ok, the error is fixed now and I cut like 200 lines of code... umm why is Keyboard.js so redundant??

**Comment by shokiami** [comment]
@misaugstad Could you also please take a look at the imports in LabelController.scala just to make sure I didn't add anything unnecessary. Thanks!

**Review by misaugstad — APPROVED** [review]
This was really well done and really clean! Really happy about the simplification of Keyboard.js in particular :) 

I only made a few small edits while reviewing
1. Moved keyboard shortcuts around a tiny bit to avoid the 'g' and 'y' keys because the underlining isn't visible below those letters.
1. Updated the Spanish text for the temporary checkbox "Temporal (p. ej., construcción)" -> "Temporal (p. ej., obra en construcción)" and then fixed the CSS a bit because that change messed with the location of the OK button.
1. I shortened the code that got the configs slightly that you had pointed me to.

**Pull request merged**
