### PR TITLE
#2150 logging in tutorial

### LINKED ISSUE #2150: Problems with logging in the tutorial
This started out just as an issue for duplicate logging in the tutorial, but now I'm just going to include all the logging problems I find.

UPDATE: Okay, actually below when I say things are being logged "2 times" what I actually mean is "2^(n+1) times", where n is the number of times you placed a label in the incorrect location. And the tagging being logged 20 times is more like 10*2^(n+1) times. If you place a label in the wrong spot more than 8 times or so, you start to see a performance hit. By the time I placed 15 or so incorrect labels, I was getting a 10 second delay for any action I performed during the tutorial.

- [x] For any transition, `Onboarding_Transition` is being logged twice. Only needs to happen once.
- [x] When adding the wrong tag, `Onboarding_Transition` is logged anywhere from 16 to 22 times with the note "onboardingTransition:redo-tag-attribute-\*". This only needs to happen once (any time someone adds a new tag). This is probably happening n times per tag or something.
- [x] Similar to the previous point, No Sidewalk label requires two tags. After you place the first one `Onboarding_Transition` is logged over 20 times with the note "onboardingTransition:tag-attribute-6".
- [x] In the above two situations where the tag stuff is being labeled a bunch of times, the `ContextMenu_Close` action is also being logged once for every two `Onboarding_Transition` actions. I'm not sure if this is happening anywhere else, but it is happening when adding/removing tags at least. Most of the time this shouldn't be logged at all because the context menu remains open after adding a tag. I know that when you add the correct tag (and remove all incorrect tags) the context menu automatically closes for you. So it might have something to do with this.
- [x] ~When we log the action `KeyboardShortcut_TagAdded` we include the note "tagId:\*,tagName:\*", but when we log the action `ContextMenu_TagAdded` (the click version of that) our note includes the audit task ID "tagId:\*,tagName:\*,auditTaskId:\*". We don't need to log the audit task ID at all, there is already a column for that.~ -- I'm realizing now that the `auditTaskId` note doesn't matter in the tutorial, but it does matter outside the tutorial, since you can go back to an old label and edit it. So the note should be kept the same.
- [x] For most situations, if you do something wrong, you go to a "redo-X" state, and that is logged. But for some reason, placing a label in the wrong location is handled by a different function in Onboarding.js instead of having its own state. This also means that it isn't being logged as such. You can tell that an error was made because the "onboardingTransition:select-label-type-\*" note gets logged extra times. But it should really have its own state like the rest of the mistakes.

The original text of the issue:
>I'm trying to get together data from the tutorial logs and I'm seeing that every Onboarding_Transition action is being logged twice. And even worse, if you choose the wrong tag, the action is being logged 16 or more times. My guess is something like it's logging it 4 times per tag for some reason.

### PR DESCRIPTION
**Pull request by rpechuk**
Resolves checkboxes 2 through 5 of #2150 

Limits logging from 10*2^n to 2n (ish better at times worse at others) in the tutorial as well as removes audit id  from the "ContextMenu_TagAdded" action.

##### Testing instructions
1.  go through tutorial
2. check the database for logs that apply

EDIT: UPDATE FROM MIKEY 7/23/2021
1. I've fixed things so that checkboxes 2 through 6 of #2150 have been fixed. (Fixes #2150)
2. I've added a "step" variable to the set of notes associated with `OnboardingTransition` logs, which should make it easier to figure out how far someone got in the tutorial during data analysis.
3. I renamed the `rate-attribute-1` log to `rate-severity-1` to match the format for the other labels.

### CODE REVIEW

**Review by misaugstad — CHANGES_REQUESTED** [review]
1. Why were `tutorial.png` and `afterwalkTutorial.png` deleted? Were they causing performance issues? Had we talked about deleting them in the past?
2. Checkbox 2 has not been resolved. The screenshot below is from adding the wrong tag on the 2nd label once and then removing it
    >When adding the wrong tag, `Onboarding_Transition` is logged anywhere from 16 to 22 times with the note "onboardingTransition:redo-tag-attribute-*". This only needs to happen once (any time someone adds a new tag).
    
    Screenshot from 2021-07-01 14-00-02
2. Checkbox 3 has not been resolved
    > Similar to the previous point, No Sidewalk label requires two tags. After you place the first one Onboarding_Transition is logged over 20 times with the note "onboardingTransition:tag-attribute-6".
    
    Screenshot from 2021-07-01 13-49-24
3. Checkbox 4 has not been resolved
    >In the above two situations where the tag stuff is being labeled a bunch of times, the ContextMenu_Close action is also being logged once for every two Onboarding_Transition actions ... Most of the time this shouldn't be logged at all because the context menu remains open after adding a tag.

    Screenshot from 2021-07-01 14-05-06
5. At least checkbox 5 seems fixed! :sweat_smile:

**Comment by rpechuk** [comment]
See above for what the db should look like and you can see how many times it's actually being called through the code in the console.

**Comment by misaugstad** [comment]
@rpechuk with the log statements you are logging the `redo-rate-attribute-2` action, but my screenshots from the database are for the `redo-tag-attribute-2` action. And I tried adding a console log statement for that action, and got the same results that I'm seeing in the database.
Screenshot from 2021-07-15 13-19-33

**Comment by rpechuk** [comment]
Hmm ok sounds good, I'll look more into it then

**Comment by rpechuk** [comment]
Letting this issue sit for now however I think the issue has to do with the `_visitAddTag()` function which is being called (by itself through the callback on line 920) which I don’t think is being removed properly so that’s why it’s called multiple times

**Review by misaugstad — APPROVED** [review]

**Comment by misaugstad** [comment]
I updated the comment at the top, but posting it down here as well!

1. I've fixed things so that checkboxes 2 through 6 of #2150 have been fixed.
2. I've added a "step" variable to the set of notes associated with `OnboardingTransition` logs, which should make it easier to figure out how far someone got in the tutorial during data analysis.
3. I renamed the `rate-attribute-1` log to `rate-severity-1` to match the format for the other labels.

**Pull request merged**
