### PR TITLE
Resolves mini-footer displaying during tutorial messages

### LINKED ISSUE #758: Mini footer visible under the onboarding intro/outro dialog box screen
Mini footer visible under the onboarding intro/outro dialog box screen. See screenshots:

Footer visible under the dialog box:
image

Closer look:
image

When deployed on the server:
image

### PR DESCRIPTION
**Pull request by sagec108**
Resolves #758.

Footer is no longer visible during intro/outro messages. The mini-footer is now visible on the loading gif page, though I can remove that if needed.

### CODE REVIEW

**Comment by sagec108** [comment]
Also fixed clicking jump and feedback buttons one after another to display the correct input boxes. Before, the user could click the two buttons, and after exiting or finishing interaction with the visible input box the user would see the other input box.

**Comment by manaswis** [comment]
@sagec108 Could you resolve conflicts?

**Comment by sagec108** [comment]
Resolved the conflicts, sorry about that.

**Comment by maddalihanumateja** [comment]
Verified on Edge and Chrome
mission_intro_before_sagec

**Comment by sagec108** [comment]
I tested this again and there are some bugs I need to fix. I'll add the fixes in another branch (does not need separate PR).

**Pull request merged**
