### PR TITLE
Made few minor updates to the admin interface

### PR DESCRIPTION
**Pull request by manaswis**
- Fixed bug in calculating number of contributing users
- Changed the ordering of the different tables on the page
- Changed the sorting order of Users Table

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Why wasn't this bug caught in code review? I don't mean this to be accusatory, I just want to improve our process...

**Comment by manaswis** [comment]
The bug would have been difficult to spot in the SQL query code. The "completed = true" part in the query was missing from registered users methods.

**Comment by manaswis** [comment]
Should I merge it?

**Comment by Soben713** [comment]
@jonfroehlich In the code review process, I generally read the code and run it to test if it works without any errors. But for the changes that affect general users (e.g. the audit page), I spend more time and check the logic to make sure there are no bugs. The pull-request that caused this bug was just for the admin page, so I didn't deeply check the logic.

**Comment by Soben713** [comment]
@manaswis Looks good, please merge it.

**Pull request merged**
